apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventstoredb.svc.headless" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "eventstoredb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: port1
      port: {{ .Values.eventstoredb.service.ports.port1.port }}
      targetPort: {{ .Values.eventstoredb.service.ports.port1.targetPort }}
      protocol: {{ .Values.eventstoredb.service.ports.port1.protocol }}
    - name: port2
      port: {{ .Values.eventstoredb.service.ports.port2.port }}
      targetPort: {{ .Values.eventstoredb.service.ports.port2.targetPort }}
      protocol: {{ .Values.eventstoredb.service.ports.port2.protocol }}
  selector:
    {{- include "eventstoredb.selectorLabels" . | nindent 4 }}