version: "3.4"

services:
  autoconfig_1:
    image: auto-config:presentation
    ports:
      - "8081:8080"
    environment:
      - REQUIREMENTS_MET_TOPIC=requirement-met-topic-1
      - RESOURCES_TOPIC=resources-topic-1
      - KAFKA_SERVER=kafka:9092
      - EVENTSTORE_HOST=eventstore_db
      - SYSTEM_CONFIG_NAME=system_config_1
    depends_on:
      - kafka
  autoconfig_2:
    image: auto-config:presentation
    ports:
      - "8082:8080"
    environment:
      - REQUIREMENTS_MET_TOPIC=requirement-met-topic-2
      - RESOURCES_TOPIC=resources-topic-2
      - KAFKA_SERVER=kafka:9092
      - EVENTSTORE_HOST=eventstore_db
      - SYSTEM_CONFIG_NAME=system_config_2
    depends_on:
      - kafka
  autoconfig_3:
    image: auto-config:presentation
    ports:
      - "8083:8080"
    environment:
      - REQUIREMENTS_MET_TOPIC=requirement-met-topic-3
      - RESOURCES_TOPIC=resources-topic-3
      - KAFKA_SERVER=kafka:9092
      - EVENTSTORE_HOST=eventstore_db
      - SYSTEM_CONFIG_NAME=system_config_3
    depends_on:
      - kafka
  eventstore_db:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_MEM_DB=true
    ports:
      - "1113:1113"
      - "2113:2113"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "9090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181